### ISSUE TITLE
Make the default polling interval 10 seconds

### ISSUE THREAD

**Issue by simontuffs** [Pogadog/anomalizer-grafana-plugin#3]
30 seconds seems like a long time to wait.  I think the backend can deliver 10 second updates, if not we need to make it so it can.

**Comment by simontuffs** [comment]
Also, the default sort-by should be "features" based on "normalized_features" aspect.

**Comment by pinky00707** [comment]
Thanks for the feedback. The default update interval can be changed down to 10 seconds, though the interval can be customized and saved from the Grafana configuration panel. As far as the default sort, it's currently "RSTD," and there currently isn't an option for normalized features. Should this be added, and if so, where can the normalized_features property be accessed?

**Comment by simontuffs** [comment]
normalized_features is under the features blob.  it's new, but it is present for all metrics now and guaranteed present. It's kind of a server-side version of the client-side sort value.

**Comment by simontuffs** [comment]
regarding 10 seconds, I think we should make that the default, otherwise you are left looking at an empty metrics panel for 30 seconds on load.  This might be due to bootstrapping the demo server.  Or maybe use 10 seconds on the first cycle, then 30 seconds thereafter, to give the anomalizer time to load.

**Comment by philiptuffs** [comment]
For simplicity's sake I've set the default interval to 10s. The interval can then be brought higher on a panel-by-panel basis if required. Let's see how it works--we can add per-cycle adjustments later if required.
