### ISSUE TITLE
Support filtering by tag on server side.

### ISSUE THREAD

**Issue by simontuffs** [Pogadog/anomalizer-grafana-plugin#4]
The goal here is to allow prometheus query tags to be passed to the query string, to reduce the amount of data returned from the server.  Prometheus query tag strings look like this: {job=\~"anomalizer", target=\~"local..*"}, kind of a pseudo regex format.

To support this we would need to add a text-box to the UI, and map it to a new /filter post parameter (server_tags). There would be no inversion required, since the server-side filter language supports it.

While this is prometheus specific, the concept would probably extend to other metrics systems that support server-side filtering of metric retrieval.

This can have a significant impact on the efficiency of processing large amounts of metrics, breaking them down into manageable chunks based on server-side tags.

This requires coordinated updates on the server side first, then the client sides.  Would like to propagate this into the standalone UI as well as the plugin,

**Comment by pinky00707** [comment]
Okay sounds cool. I'll begin working on it

**Comment by pinky00707** [comment]
Just to clarify about what kind of input you wanted. Did you want a text box in the Grafana panel options that allowed you to enter `{job=~"anomalizer", target=~"local..*"}` or did you want some kind of advanced tag picker?

**Comment by simontuffs** [comment]
uncommitted text box: the expressions can be quite general, and will be
specific to the backend. right now we are just doing prometheus, but
eventually we will target the other time-series databases (influxdb,
opentsdb, yada yada yada). There are a lot.

**Comment by pinky00707** [comment]
Okay sounds good

**Comment by simontuffs** [comment]
Aha, I think I'm going to retract this request for now, it is possible to get the net result by having the setting panel and visualization open at the same time. For some reason this wasn't happening when I first tested it, but I have tested in Grafana 7.0.0 and latest (8.4.5) and apart from the expected changes in how you pick a visualization, everything works nicely.

![Uploading Screen Shot 2022-08-28 at 12.52.51 PM.png…]()

**Comment by simontuffs** [comment]
server_tags are now live in the cloud:

<img width="548" alt="Screen Shot 2022-08-28 at 12 58 39 PM" src="https://user-images.githubusercontent.com/285867/187092269-accefced-8cc5-4e4e-8c76-7d4e0d1e2d95.png">

**Comment by pinky00707** [comment]
Thanks, just need something to test the requests
