### ISSUE TITLE
Add a data-connector for the Anomalizer backend

### ISSUE THREAD

**Issue by simontuffs** [Pogadog/anomalizer-grafana-plugin#5]
Currently the plugin has the anomalizer endpoint in its settings panel. The usual patter for Grafana Plugins is that they utilize a data-source to define the backend resources, rather than defining themselves. This allows a group of panels to be switched to a new data-source by modifying information in a single place.

So, we need to move the "Anomalizer Endpoint" field into the data-source, and replace it with a data-source selector that is of type "Anomalizer".

**Comment by pinky00707** [comment]
Agreed. This is a good long-term project to further integrate with Grafana infrastructure.

**Comment by philiptuffs** [comment]
Looks like I'll need to create a data-source plugin for Grafana. I'll publish a repo with a working draft soon. Depending on how the development of it goes, this issue may not be ready in time for our beta 0 release.

**Comment by simontuffs** [comment]
Let’s try to get this done, otherwise it will be disruptive to early
adopters.

**Comment by simontuffs** [comment]
The latest build of the datasource and plugin work together nicely. I'm closing this issue.
